app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors  # noqa

app/main/views.py
from flask import render_template, flash
from flask_login import login_required
from ..models import EditableHTML, Api
from .. import db
from . import main


@main.route('/')
def index():
    return render_template('main/index.html')

@main.route('/home')
def home():
    return render_template('main/home.html')

@main.route('/about')
def about():
    editable_html_obj = EditableHTML.get_editable_html('about')
    return render_template('main/about.html', editable_html_obj=editable_html_obj)

app/templates/main/about.html
{% import 'macros/page_macros.html' as page %}
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="ui text container">
        <h1>About</h1>
        {{ page.render_inline_editor(editable_html_obj, current_user) }}
    </div>

    <script src="{{ url_for('static', filename='ckeditor/ckeditor.js') }}"></script>
{% endblock %}

app/templates/main/home.html
{% extends 'layouts/base.html' %}

{% macro dashboard_option(title, endpoint, description=None, icon=None) %}
    <a class="column" href="{{ url_for(endpoint) }}">
        <div class="ui padded segment">
            <h3 class="ui header">
                {% if icon is not none %}
                    <i class="{{ icon }}"></i>
                {% endif %}
                <div class="content">
                    {{ title }}
                    {% if description is not none %}
                        <div class="sub header">
                            {{ description }}
                        </div>
                    {% endif %}
                </div>
            </h3>
        </div>
    </a>
{% endmacro %}

{% block content %}
<div class="ui text container">
    <h1>Home</h1>
      <div class="ui three column stackable grid">
          {{ dashboard_option('Call APIs', 'request.searchForApi',
                              description=None, icon=None) }}
          {{ dashboard_option('View APIs', 'api.index',
                              description=None, icon=None) }}
          {{ dashboard_option('View Parameters', 'parameter.index',
                              description=None, icon=None) }}
          {{ dashboard_option('Add API', 'api.add_api',
                              description=None, icon=None) }}
          {{ dashboard_option('Add Parameter', 'parameter.add',
                              description=None, icon=None) }}
      </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="ui text container">
      <h1>Legal Checkup</h1>
      <button class="ui button">Register</button>
      <a href="{{ url_for('main.home')}}"><button class="ui button">Login</button></a>
    </div>
{% endblock %}