app/models/api.py
from .. import db

class ApiParameterLink(db.Model):
    __tablename__ = 'api_parameter_link'
    api_id = db.Column(db.Integer, db.ForeignKey('apis.id'), primary_key=True)
    parameter_id = db.Column(db.Integer, db.ForeignKey('parameters.id'), primary_key=True)
    parameter_description = db.Column(db.String(128))
    api = db.relationship('Api', backref='parameter_associations')
    parameter = db.relationship('Parameter', backref='api_associations')

    def __init__(self, api, param, description):
        self.api = api
        self.parameter = param
        self.parameter_description = description
        param.incr_count

    def __repr__(self):
        return '<ApiParameterLink \'%s %s %s\'>' % (self.api.name, self.parameter.name,
            self.parameter_description)

class Api(db.Model):
    __tablename__ = 'apis'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    url = db.Column(db.String(128), unique=True)
    region = db.Column(db.String(64))
    description = db.Column(db.String(128))
    parameters = db.relationship('Parameter', secondary='api_parameter_link')

    def add_param(self, param, description):
        self.parameter_associations.append(ApiParameterLink(api=self,
            param=param, description=description))

    def get_params(self):
        param_links = ApiParameterLink.query.filter_by(api_id=self.id).all()
        params = []
        for link in param_links:
            params.append(link.parameter)
        return params

    def __init__(self, name, url, region, description):
        self.name = name
        self.url = url
        self.region = region
        self.description = description

    def __repr__(self):
        return '<Api \'%s %s %s %s\'>' % (self.name, self.url, self.region, self.description)

class Parameter(db.Model):
    __tablename__ = 'parameters'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    param_format = db.Column(db.String(64))
    count = db.Column(db.Integer)
    apis = db.relationship('Api', secondary='api_parameter_link')

    def get_apis(self):
        return ApiParameterLink.query.filter_by(parameter_id=self.id).all()

    def incr_count(self):
        self.count += 1

    def __init__(self, name, param_format, count):
        self.name = name
        self.param_format = param_format
        self.count = count

    def __repr__(self):
        return '<Parameter \'%s %s %s\'>' % (self.name, self.param_format,
            self.count)

app/api/forms.py
from flask_wtf import Form
from wtforms.fields import (
    BooleanField,
    FieldList,
    FormField,
    SelectField,
    SelectMultipleField,
    SubmitField,
    TextAreaField,
    TextField
)
from wtforms.validators import InputRequired, Length

class ParameterForm(Form):
    param_name = TextField('Parameter Name', validators=[InputRequired(), Length(1, 500)])
    description = TextField('Description', validators=[InputRequired(), Length(1, 500)])
    param_format = TextField('Format', validators=[InputRequired(), Length(1, 500)])

class NewAPIForm(Form):
    name = TextField('Name of API', validators=[InputRequired(), Length(1, 500)])
    region = SelectField('Region',
                            choices=[('Philadelphia', 'Philadelphia'), ('Pennsylvania', 'Pennsylvania')],
                            validators=[InputRequired()]
                            )
    # Parameters are dynamically populated when rendered -- see views.py.
    parameters = SelectMultipleField('Parameters',
                            choices=[],
                            validators=[])
    # TODO: Removing parameters
    new_parameter = FieldList(FormField(ParameterForm), min_entries=0)
    add_parameter = SubmitField('Add a new parameter')
    url = TextField('API URL', validators=[InputRequired(), Length(1, 500)])
    description= TextAreaField('Description')
    submit = SubmitField('Add API')

app/request/forms.py
from flask import url_for
from flask_wtf import Form
from wtforms import ValidationError
from wtforms.fields import (BooleanField, PasswordField, StringField,
                            SubmitField)
from wtforms.fields.html5 import EmailField
from wtforms.validators import Email, EqualTo, InputRequired, Length

from ..models import Api

class SearchForm(Form):
    api = StringField('API', validators=[InputRequired()])
    submit = SubmitField('Search')

class ParamsForm(Form):
    # api = StringField('API', validators=[InputRequired()])
    submit = SubmitField('Submit')

app/api/__init__.py
from flask import Blueprint

api = Blueprint('api', __name__)

from . import views  # noqa
from . import forms  # noqa

app/api/views.py
from flask import flash, jsonify, redirect, render_template, url_for
from ..models import EditableHTML, Api, ApiParameterLink, Parameter

from flask_login import login_required
from sqlalchemy.exc import IntegrityError
from wtforms.fields import SelectField
from flask_wtf.file import InputRequired
import requests

import sys # For debugging

from .forms import (
    NewAPIForm,
    ParameterForm
)

from .. import db
from . import api
from ..models import Parameter

@api.route('/')
def index():
    """View all apis."""
    apis = Api.query.all()
    return render_template('api/index.html', apis=apis)

def get_all_params():
    params = Parameter.query.all()
    choices_to_return = []
    for param in params:
        choices_to_return.append((param.name, param.name))
    return choices_to_return

@api.route('/add', methods=['GET', 'POST'])
def add_api():
    """Create a new API."""
    form = NewAPIForm()
    form.parameters.choices = get_all_params()

    if form.add_parameter.data:
        form.new_parameter.append_entry()

    if form.submit.data and form.validate_on_submit():
        new_api = Api(
            name=form.name.data,
            region=form.region.data,
            description=form.description.data,
            url=form.url.data
        )

        # Links the parameters to the new API.
        for param_data in form.parameters.data:
            param = Parameter.query.filter_by(name=param_data).first()
            if param is not None:
                # TODO: Ask users to give a param description when adding params.
                new_api.add_param(param, "Parameter-description")

        # Creates the new parameters and links them to the API.
        for new_param in form.new_parameter:
            param = Parameter(
                name=new_param.param_name.data,
                param_format=new_param.param_format.data,
                count=0
                )
            new_api.add_param(param, new_param.description)

        db.session.add(new_api)
        try:
            db.session.commit()
            flash('API {} successfully added'
                      .format(new_api.name),
                      'form-success')
            return redirect(url_for('api.index'))
        except IntegrityError:
            db.session.rollback()
            flash('Database error occurred. Please try again.',
                  'form-error')
    return render_template('api/add.html', form=form)

@api.route('/info', methods=['GET'])
def get_api_info_all():
    apis = Api.query.all()
    apis_to_jsonify = []
    for api in apis:
        apis_to_jsonify.append(get_api_info(api.id))
    return jsonify({'APIs': apis_to_jsonify})

@api.route('/info/<int:api_id>', methods=['GET'])
def get_api_info(api_id):
    id = Api.query.get_or_404(api_id)
    return jsonify({
        'name': id.name,
        'region': id.region,
        'description' : id.description,
        'url': id.url,
        'parameters': [ p.name for p in id.get_params() ]
        })

@api.route('/request/<string:api_name>', methods=['GET'])
def get_api_name(api_name):
    url = Api.query.get_or_404(api_name)
    r = request.head(url)
    if r.status_code != 200:
        return render_template('api/requests.html')
    return redirect(url_for('api.name'))

app/request/__init__.py
from flask import Blueprint

request = Blueprint('request', __name__)

from . import views, forms  # noqa

app/request/views.py
import requests
from flask import render_template, flash, request, jsonify, redirect, url_for
from ..models import EditableHTML, Api
from . import request
from .forms import (SearchForm, ParamsForm)

from wtforms.fields import (BooleanField, PasswordField, StringField,
                            SubmitField)

@request.route('/search', methods=['GET', 'POST'])
def searchForApi():
    """Search for an API"""
    searchForm = SearchForm()
    if searchForm.validate_on_submit():
        apiName = searchForm.api.data
        # Api.query.filter_by(name=name) # TODO: get params from db
        return redirect(url_for('request.searchData'))
    return render_template('api/search.html', form=searchForm)


@request.route('/search_params', methods=['GET', 'POST'])
def searchData():
    apiName = SearchForm().api.data
    # params = [
    #     {'name': "s", 'param_format': "String"},
    #     {'name': "y", 'param_format': "Year"}
    #     ]

    params = [
        {'name': "Title", 'param_format': "String"},
        {'name': "Year", 'param_format': "Year"}
        ]

    paramForm = ParamsForm()
    for param in params:
        field = StringField(param['name'])
        setattr(ParamsForm, param['name'], field)

    if paramForm.validate_on_submit():
        url = 'http://www.omdbapi.com/'
        #TODO: get url from db
        paramData = {}
        for param in params:
            pName = param['name']
            paramData[pName] = paramForm[pName].data

        paramData['s'] = paramForm['Title'].data
        paramData['y'] = paramForm['Year'].data

        r = requests.get(url, params=paramData)
        data = r.content
        # print(data
        # for key in data:
            # print(data[key])
        return render_template('api/search_data.html', data=data)
    return render_template('api/search_params.html', form=paramForm, params=params, apiName = apiName)

app/templates/api/add.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block content %}
    <div class="ui text container">
        <h1>Add API</h1>
        <div class="add api">
            {% set flashes = {
                'error':   get_flashed_messages(category_filter=['form-error']),
                'warning': get_flashed_messages(category_filter=['form-check-email']),
                'info':    get_flashed_messages(category_filter=['form-info']),
                'success': get_flashed_messages(category_filter=['form-success'])
            } %}

            {{ f.begin_form(form, flashes) }}

                {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
                {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
                {{ f.form_message(flashes['info'], header='Information', class='info') }}
                {{ f.form_message(flashes['success'], header='Success!', class='success') }}

                {{ f.render_form_field(form.name) }}

                {{ f.render_form_field(form.url)}}

                {{ f.render_form_field(form.region) }}

                {{ f.render_form_field(form.parameters) }}

                {% for param in form.new_parameter %}
                  {% for field in param if field.widget.input_type != 'hidden' %}
                    {{ f.render_form_field(field) }}
                  {% endfor %}
                {% endfor %}

                {{ f.render_form_field(form.add_parameter) }}

                {{ f.render_form_field(form.description) }}

                {{ f.render_form_field(form.submit) }}

            {{ f.end_form() }}
        </div>
    </div>
{% endblock %}

app/templates/api/index.html
{% extends 'layouts/base.html' %}
{% block content %}
    <div class="ui text container">
        <h1>API Index</h1>
    	<h1>View All API's</h1>
        <table class="ui searchable sortable unstackable selectable celled table">
          <thead>
            <tr>
              <th>Name</th>
    	        <th>Description</th>
              <th>URL</th>
            </tr>
          </thead>
          <tbody>
            {% for api in apis %}
            <tr>
              <td>
                  <a href="{{ url_for('api.get_api_info', api_id=api['id']) }}">{{ api['name']}}</a>
              </td>
              <td>
                  {{ api['description']}}
              </td>
              <td>
                  {{ api['url']}}
              </t>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <a href="{{ url_for('api.add_api') }}"><button class="ui button">Add API</button></a>
    </div>
{% endblock %}

app/templates/api/requests.html
{% extends 'layouts/base.html' %}
{% block content %}
{% endblock %}

app/templates/api/search_data.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block content %}
    <div class="ui stackable centered grid container">
      <div class="twelve wide column"
        <h2 class="ui header">
          Search API's
        </h2>

        <br>
        {{ data }}



      </div>
    </div>
{% endblock %}

app/templates/api/search_params.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block content %}
    <div class="ui stackable centered grid container">
      <div class="twelve wide column"
        <h2 class="ui header">
          Search API's
        </h2>

        {% set flashes = {
            'error':   get_flashed_messages(category_filter=['form-error']),
            'warning': get_flashed_messages(category_filter=['form-check-email']),
            'info':    get_flashed_messages(category_filter=['form-info']),
            'success': get_flashed_messages(category_filter=['form-success'])
        } %}

        {{ f.begin_form(form, flashes) }}
          {% for param in params %}
            {% set n = param['name'] %}
            {{ f.render_form_field(form[n]) }}
            {# TODO: display param.param_format #}
          {% endfor%}
          {{ f.render_form_field(form.submit) }}
        {{ f.end_form() }}

      </div>
    </div>
{% endblock %}