app/parameter/forms.py
from flask_wtf import Form
from wtforms.fields import (
    SubmitField,
    TextField
)
from wtforms.validators import InputRequired, Length

class ParameterForm(Form):
    name = TextField('Parameter Name', validators=[InputRequired(), Length(1, 500)])
    param_format = TextField('Format', validators=[InputRequired(), Length(1, 500)])
    submit = SubmitField('Add Parameter')

app/parameter/__init__.py
from flask import Blueprint

parameter = Blueprint('parameter', __name__)

from . import forms, views

app/parameter/views.py
from flask import flash, jsonify, redirect, render_template, request
from flask_login import login_required
from flask_restful import Resource, Api
from flask_wtf.file import InputRequired
from sqlalchemy.exc import IntegrityError
from wtforms.fields import SelectField

from ..models import EditableHTML, Parameter
from .forms import (
    ParameterForm
)

from .. import db
from . import parameter

@parameter.route('/')
def index():
    """View all parameters."""
    params = Parameter.query.all()
    return render_template('parameter/index.html', params=params)

@parameter.route('/add', methods=['GET', 'POST'])
def add():
    """Add parameter."""
    form = ParameterForm()
    if form.validate_on_submit():
        new_param = Parameter(
            name=form.name.data,
            param_format=form.param_format.data,
            count=0
        )
        db.session.add(new_param)
        try:
            db.session.commit()
            flash('Parameter successfully added',
                        'form-success')
            return redirect('parameter/')
        except IntegrityError:
            db.session.rollback()
            flash('Database error occurred. Please try again.',
                  'form-error')
    return render_template('parameter/add.html', form=form)

@parameter.route('/info/<int:param_id>', methods=['GET'])
def get_parameter_info(param_id):
    id = Parameter.query.get_or_404(param_id)
    return jsonify({'name': id.name, 'format': id.param_format, 'count': id.count})

@parameter.route('/info', methods=['GET'])
def get_parameter_info_all():
    params = Parameter.query.all()
    params_to_jsonify = []
    for param in params:
        params_to_jsonify.append({'name': param.name, 'format': param.param_format, 'count': param.count})
    return jsonify({'parameters': params_to_jsonify})


@parameter.route('/request/<string:param_name>', methods=['GET'])
def get_parameter_api(param_name):
    apis = Parameter.query.get_or_404(param_name)
    all_api_urls = []
    for api in apis:
        r = request.head(url)
        if r.status_code != 200:
            continue
        all_api_urls.append(url_for(api.id))
    return all_api_urls

app/templates/parameter/add.html
{% extends 'layouts/base.html' %}
{% import 'macros/form_macros.html' as f %}

{% block content %}
<div class="ui text container">
  <h1>Add Parameter</h1
    <div class="add param">
      {% set flashes = {
        'error':   get_flashed_messages(category_filter=['form-error']),
        'warning': get_flashed_messages(category_filter=['form-check-email']),
        'info':    get_flashed_messages(category_filter=['form-info']),
        'success': get_flashed_messages(category_filter=['form-success'])
      } %}

      {{ f.begin_form(form, flashes) }}

      {{ f.form_message(flashes['error'], header='Something went wrong.', class='error') }}
      {{ f.form_message(flashes['warning'], header='Check your email.', class='warning') }}
      {{ f.form_message(flashes['info'], header='Information', class='info') }}
      {{ f.form_message(flashes['success'], header='Success!', class='success') }}

      {{ f.render_form_field(form.name) }}

      {{ f.render_form_field(form.param_format) }}

      {{ f.render_form_field(form.submit) }}

      {{ f.end_form() }}
    </div>
  </div>
  {% endblock %}

app/templates/parameter/index.html
{% extends 'layouts/base.html' %}

{% block content %}
    <div class="ui text container">
        <h1>View All Parameters</h1>
        <table class="ui searchable sortable unstackable selectable celled table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Format</th>
            </tr>
          </thead>
          <tbody>
            {% for param in params %}
            <tr>
              <td>
                  <a href="{{ url_for('parameter.get_parameter_info', param_id=param['id']) }}">{{ param['name']}}</a>
              </td>
              <td>
                {{ param['param_format']}}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <a href="{{ url_for('parameter.add') }}"><button class="ui button">Add Parameter</button></a>
    </div>
{% endblock %}